name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s);
           docker run -t my-image-name:$(date +%s) /bin/bash;
           docker exec /t my-image-name:$(date +%s) /bin/bash /c \"cd test; /GLM/glm\"
